#!/bin/sh /etc/rc.common

START=98
NAME=gmediarender

PID_FILE=/var/run/$NAME.pid
LOG_FILE=/var/log/$NAME.log

handle_gmediaplay() {
	local config="$1"

	config_get bname "$1" bname "gmediaplay"
	config_get ipaddr "$1" ipaddr "192.168.1.1"

	mac=`ifconfig | awk '/HWaddr/{ print $5;exit }' | sed 's/://g'`

	service_start /usr/bin/$NAME -I "$ipaddr" -f "$bname" -u "e6572b54-f3c7-2d91-2fb5-"$mac -d -P $PID_FILE --logfile $LOG_FILE
}

start() {
	config_load gmediarender
	local enabled
	config_get enabled config enabled
	[ $enabled -eq 0 ] && {
		stop
		return 0
	}

	config_load gmediaplay
	config_foreach handle_gmediaplay gmediaplay
}

stop() {
	# kill -9 `cat $PID_FILE` > /dev/null 2>&1
	service_stop /usr/bin/$NAME
	rm -rf $PID_FILE
}
