--- Makefile	2013-12-05 13:56:00.394683418 +0800
+++ Makefile	2013-12-05 13:57:19.990687241 +0800
@@ -49,7 +49,7 @@
   SECTION:=libs
   SUBMENU:=SSL
   CATEGORY:=Libraries
-  DEPENDS:=+zlib
+  DEPENDS:=+zlib +libpthread
   TITLE+= (libraries)
   MENU:=1
 endef
@@ -123,7 +123,7 @@
 	)
 endef
 
-TARGET_CFLAGS += $(FPIC)
+TARGET_CFLAGS += $(FPIC) -DOPENSSL_THREADS -pthread -D_REENTRANT -D_THREAD_SAFE -D_THREADSAFE
 
 define Build/Compile
 	# XXX: OpenSSL "make depend" will look for installed headers before its own,
